N = 3

Vagrant.configure("2") do |config|
  (1..N).each do |i|
    config.vm.define "kafka-sever-#{i}" do |cfg|
      cfg.vm.box = "hashicorp/bionic64"
      cfg.vm.box_version = "1.0.282"
      cfg.vm.provider "virtualbox" do |vb|
        vb.name = "kafka-sever-#{i}"
        vb.cpus = 1
        vb.memory = 1536
        vb.customize ["modifyvm", :id, "--groups", "/infra"]
      end
      cfg.vm.host_name = "kafka-sever-#{i}"
      cfg.vm.network "private_network", ip: "192.168.29.20#{i}"
      cfg.vm.synced_folder "../data", "/vagrant", disabled: true
      cfg.vm.provision "shell", path: "kafka_install.sh", args: [ "#{i}00" ]
    end
  end
end