# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  #===========#
  # MySQL 8.0 #
  #===========#
  config.vm.define "mysql8.0-server" do |cfg|
    cfg.vm.box = "hashicorp/bionic64"
    cfg.vm.box_version = "1.0.282"
    cfg.vm.provider "virtualbox" do |vb|
      vb.name = "mysql8.0-server"
      vb.cpus = 1
      vb.memory = 1536
      vb.customize ["modifyvm", :id, "--groups", "/infra"]
    end
    cfg.vm.host_name = "mysql8.0-server"
    cfg.vm.network "private_network", ip: "192.168.29.15"
    cfg.vm.synced_folder "../data", "/vagrant", disabled: true
    cfg.vm.provision "docker" do |d|
      d.run "mysql:8.0.32", args: "-p 3306:3306 -e MYSQL_ROOT_PASSWORD=password -v mysql:var/lib/mysql"
    end
  end
end
