# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  #============#
  # MySQL 8.0  #
  #============#
  config.vm.define "nfs-server" do |cfg|
    cfg.vm.box = "hashicorp/bionic64"
    cfg.vm.box_version = "1.0.282"
    cfg.vm.provider "virtualbox" do |vb|
      vb.name = "mysql-server"
      vb.cpus = 2
      vb.memory = 2024
      vb.customize ["modifyvm", :id, "--groups", "/infra"]
    end
    cfg.vm.host_name = "nfs-server"
    cfg.vm.network "private_network", ip: "192.168.29.14"
    cfg.vm.synced_folder "../data", "/vagrant", disabled: true
    cfg.vm.provision "shell", path: "nfs_server_init.sh"
  end
end
